services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=distbank_concurrency'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432'
