global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'grpc_server'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          protocol: 'grpc'

  - job_name: 'json_rpc_server'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          protocol: 'json-rpc'
